VAGRANTFILE_API_VERSION = "2"

Vagrant.require_version ">= 1.5.0"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "valtech_sweden/ubuntu-trusty64"
  config.vm.box_version = "~> 0.1.1"
  config.vm.provision :shell, :path => "bootstrap.sh"
  config.vm.network "forwarded_port", guest: 5000, host: 55066
  config.vm.synced_folder "./", "/app"
end
